USE Team8NordstromDB

-- ALTER TABLE tblStore

insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (115, 'Bloomington Mall of America', '8179 Pawling Park', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (213, 'Cheyenne Frontier Store', '29868 Coleman Street', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (273, 'Dover First State Plaza', '9459 Dawn Pass', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (199, 'Helena Big Sky Shop', '50 Calypso Circle', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (164, 'Baltimore Harbor Shop', '76609 Dexter Park', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (217, 'Toronto Maple Square', '99744 Buhler Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (75, 'Boston Harbor Shop', '38 Gulseth Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (276, 'Savannah Mossy Oak Boutique', '2857 Melody Junction', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (35, 'Vancouver Harbor Retail', '27181 Green Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (235, 'Milwaukee Lakeside Outlet', '3 Thackeray Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (55, 'Tulsa Golden Gateway', '01 Monica Drive', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (224, 'Manchester Granite Shop', '2 Blackbird Crossing', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (162, 'Bridgeport Coastal Junction', '7164 Rusk Trail', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (350, 'Washington Capitol Storefront', '0755 Sherman Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (236, 'Boise Riverwalk Market', '43 Oakridge Point', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (172, 'Las Vegas Strip Retail', '68356 Summer Ridge Place', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (168, 'Portland Casco Bay Store', '9 Karstens Center', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (264, 'Fargo Frontier Shop', '6566 Shoshone Center', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (12, 'Pasadena Rose Court Boutique', '7 Novick Center', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (219, 'St. Cloud River City Store', '75 Kingsford Parkway', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (20, 'Cheyenne Frontier Store', '44004 Rockefeller Point', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (61, 'Long Beach Pacific View Store', '08742 International Hill', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (130, 'Pensacola Beachfront Boutique', '0748 Northwestern Avenue', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (82, 'Springfield Lincoln Land Store', '92537 Fair Oaks Park', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (77, 'Lubbock Lonestar Plaza', '7 Anthes Trail', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (250, 'Akron Rubber City Shop', '60741 Crownhardt Trail', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (159, 'Vancouver Harbor Retail', '266 Vermont Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (309, 'Tampa Bay Treasures', '05827 Porter Avenue', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (39, 'Springfield Lincoln Land Store', '425 Hoffman Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (84, 'Manchester Granite Shop', '29 Moulton Point', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (146, 'Dallas Lone Star Center', '26 Declaration Road', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (38, 'New Haven Elm Street Retail', '562 Red Cloud Center', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (243, 'Mobile Gulf Coast Store', '8 Huxley Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (324, 'Cedar Rapids Corn City Shop', '31132 Independence Drive', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (291, 'Mobile Bay Store', '685 Vahlen Point', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (34, 'Boston Harbor Shop', '6089 Emmet Place', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (25, 'Louisville Riverfront Shop', '3 Grover Point', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (203, 'Anchorage Northern Lights Market', '18478 Morning Terrace', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (215, 'Boston Harbor Shop', '36014 Oak Valley Point', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (17, 'Salt Lake City Wasatch Store', '12773 Prairie Rose Avenue', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (54, 'Roanoke Star City Shop', '28 Muir Terrace', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (319, 'Billings Big Sky Shop', '9928 Clarendon Avenue', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (85, 'Fashion Island', '782 Schurz Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (301, 'Billings Big Sky Shop', '50 Bonner Trail', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (290, 'Atlanta Peachtree Plaza', '4 Roth Point', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (317, 'Miami Beach Outpost', '199 Crescent Oaks Point', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (301, 'Albuquerque Sunset Plaza', '67539 Prairie Rose Pass', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (129, 'Helena Big Sky Shop', '48692 Anderson Center', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (35, 'Grand Rapids Furniture City Shop', '2142 Grasskamp Road', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (150, 'Portland Casco Bay Store', '7490 Pierstorff Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (334, 'Montreal Cultural Hub', '78 Veith Place', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (134, 'Little Rock Diamond Mall', '19 Dixon Junction', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (80, 'Pasadena Rose Court Boutique', '30263 Esch Drive', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (294, 'Louisville Riverfront Shop', '81 Pine View Road', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (327, 'Portland Casco Bay Store', '1894 Bowman Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (93, 'Spokane Riverfront Mall', '5 Sauthoff Crossing', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (57, 'Greensboro Gate City Boutique', '1 Messerschmidt Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (352, 'Myrtle Beach Palmetto Place', '739 Schlimgen Street', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (39, 'Sacramento Valley View', '739 Claremont Alley', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (208, 'Anchorage Northern Lights Market', '46 Katie Lane', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (308, 'Carson City Silver State Boutique', '7 Jana Hill', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (201, 'Mobile Gulf Coast Store', '8 Schurz Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (124, 'Pasadena Rose Court Boutique', '53712 Hansons Alley', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (243, 'Peoria Riverfront Plaza', '29823 Declaration Court', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (247, 'Roanoke Star City Shop', '834 Meadow Vale Road', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (226, 'St. Cloud River City Store', '82 Ronald Regan Court', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (38, 'Knoxville Smoky Mountain Boutique', '09 Clove Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (131, 'Fargo Frontier Shop', '84293 Clyde Gallagher Avenue', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (5, 'Dallas Lone Star Center', '97 Clemons Road', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (97, 'Las Vegas Strip Retail', '59400 1st Crossing', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (126, 'Jackson Magnolia Mall', '69 Truax Road', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (314, 'Dallas Lone Star Center', '19 Village Parkway', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (191, 'Tallahassee Capital Collection', '4320 Mandrake Terrace', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (20, 'Lexington Bluegrass Boutique', '0 Morrow Junction', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (2, 'Birmingham Iron City Mall', '1 Buena Vista Trail', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (335, 'Cheyenne Frontier Store', '5596 Nevada Alley', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (337, 'Shreveport Red River Retail', '954 Old Shore Terrace', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (62, 'Virginia Beach Surfside Store', '608 Lake View Alley', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (352, 'Boise Riverwalk Market', '5440 Portage Road', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (358, 'Boise Riverwalk Market', '1632 Nancy Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (276, 'Baltimore Harbor Shop', '8 Swallow Circle', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (320, 'Yonkers Hudson Line Store', '740 Stuart Court', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (137, 'Wichita Windflower Boutique', '71021 Manufacturers Avenue', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (325, 'Washington Capitol Storefront', '9 Harbort Parkway', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (202, 'Virginia Beach Surfside Store', '02965 Washington Center', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (345, 'Boise Capital Mall', '2 New Castle Center', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (48, 'Helena Big Sky Shop', '4091 Katie Plaza', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (271, 'Denver Mountain Mall', '9 Jenna Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (193, 'Phoenix Desert Oasis', '173 Leroy Center', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (334, 'Milwaukee Lakeside Outlet', '39 Linden Crossing', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (154, 'Bismarck Northern Plains Outlet', '24 Dawn Trail', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (80, 'Bellevue Square', '23 Beilfuss Crossing', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (354, 'Tulsa Oil Capital Boutique', '810 Bunting Alley', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (263, 'Columbus Arch City Store', '533 Hanson Place', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (239, 'Orlando Magic Mart', '4528 Fairfield Center', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (215, 'Knoxville Smoky Mountain Boutique', '76 Roth Hill', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (35, 'Boise Capital Mall', '8 7th Crossing', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (336, 'Billings Yellowstone Outlet', '28 Elka Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (128, 'Madison Dairyland Boutique', '6041 Northfield Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (250, 'Albuquerque Sunset Plaza', '2598 Birchwood Road', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (6, 'NYC Flagship', '054 Bayside Trail', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (170, 'Tulsa Oil Capital Boutique', '410 Mitchell Parkway', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (5, 'Minneapolis Twin Lakes Outlet', '3 Birchwood Court', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (212, 'Boise Riverwalk Market', '81334 Westerfield Alley', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (204, 'Flagstaff Ponderosa Mall', '896 Pond Crossing', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (177, 'San Francisco Bay Boutique', '41 Southridge Way', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (242, 'Tucson Desert Jewel Store', '27 Towne Pass', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (249, 'Fargo Frontier Shop', '575 Moland Parkway', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (31, 'Wichita Windflower Boutique', '78 Veith Plaza', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (334, 'Lincoln Star City Market', '765 Katie Court', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (284, 'Amarillo Canyon View Market', '0575 Rockefeller Junction', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (275, 'Little Rock Diamond Mall', '161 Cambridge Hill', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (51, 'Milwaukee Lakeside Outlet', '387 Bobwhite Point', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (166, 'Denver Mountain Mall', '429 Farwell Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (360, 'St. Petersburg Coastal Mall', '51 Havey Road', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (20, 'Nashville Music Row Mart', '99034 Sutteridge Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (165, 'New Haven Elm Street Retail', '2 Forest Dale Parkway', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (219, 'Billings Yellowstone Outlet', '1536 Tony Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (15, 'Pensacola Beachfront Boutique', '4818 Roth Hill', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (93, 'Spokane Riverfront Mall', '7 Golden Leaf Park', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (119, 'Sioux Falls Rushmore Mall', '51662 Maple Crossing', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (313, 'Billings Yellowstone Outlet', '07297 Esker Circle', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (308, 'Tampa Bay Treasures', '3 Kennedy Place', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (229, 'Cedar City Festival Market', '2204 Ridgeway Parkway', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (79, 'Savannah Mossy Oak Boutique', '35151 Green Ridge Junction', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (170, 'Boulder Flatiron Boutique', '80045 Green Ridge Plaza', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (311, 'Boise Gem State Store', '35 Lillian Center', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (175, 'Baltimore Harbor Shop', '65 Marcy Pass', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (177, 'Baltimore Harbor Shop', '80072 Sage Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (54, 'Savannah Mossy Oak Boutique', '26 Golf Course Trail', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (109, 'Yonkers Hudson Line Store', '955 Tennessee Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (138, 'New Haven Elm Street Retail', '6988 Swallow Lane', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (152, 'Peoria Riverfront Plaza', '29473 Northview Plaza', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (116, 'Wichita Windflower Boutique', '218 Welch Road', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (307, 'Minneapolis Twin Lakes Outlet', '17 Toban Point', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (82, 'Erie Lakefront Mall', '992 Sunfield Junction', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (142, 'Santa Barbara Riviera Retail', '6886 Algoma Avenue', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (21, 'Charleston Southern Charm Boutique', '905 Sachtjen Center', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (147, 'Salt Lake City Peaks Boutique', '15 Prentice Circle', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (356, 'Modesto Central Valley Plaza', '9 Cottonwood Alley', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (82, 'Des Moines Cornfield Collection', '5566 Grim Plaza', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (71, 'Shreveport Red River Retail', '17390 Helena Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (326, 'Baltimore Harbor Shop', '3 Londonderry Parkway', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (299, 'Minneapolis Twin Lakes Outlet', '58648 Northport Drive', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (90, 'Green Bay Packerland Boutique', '95437 Westridge Crossing', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (90, 'Portland Rose Garden Boutique', '8052 Helena Street', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (350, 'Rapid City Black Hills Market', '1822 John Wall Road', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (246, 'Salt Lake City Wasatch Store', '6 Becker Alley', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (239, 'San Diego Seaport Village', '53 Esch Plaza', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (79, 'Austin Live Music Store', '89 Moland Place', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (283, 'Long Beach Pacific View Store', '93946 Hazelcrest Junction', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (116, 'Myrtle Beach Palmetto Place', '90716 Spohn Crossing', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (203, 'Albuquerque Sunset Plaza', '6 Corry Center', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (310, 'Sioux Falls Rushmore Mall', '22342 Golf Course Alley', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (127, 'Mobile Bay Store', '95692 Autumn Leaf Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (192, 'Fargo Frontier Shop', '035 Thompson Junction', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (95, 'Boise Capital Mall', '3514 Merry Plaza', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (331, 'St. Cloud River City Store', '5 Burning Wood Avenue', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (139, 'Boise Riverwalk Market', '389 Maryland Way', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (214, 'Cedar Rapids Corn City Shop', '9 Bunting Junction', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (200, 'Greensboro Gate City Boutique', '24961 Alpine Alley', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (332, 'Lincoln Star City Market', '9 Ryan Park', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (19, 'Tucson Desert Jewel Store', '42 Paget Plaza', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (220, 'Corpus Christi Bayfront Shop', '53822 Kensington Junction', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (36, 'Richmond Old Dominion Boutique', '66 Laurel Center', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (340, 'Olympia Evergreen Market', '541 Village Green Lane', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (28, 'St. Louis Gateway Boutique', '5 Valley Edge Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (305, 'Montreal Cultural Hub', '3 Service Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (263, 'Sioux Falls Rushmore Mall', '86 Marcy Lane', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (1, 'Sacramento Valley View', '6 Sommers Drive', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (269, 'Baton Rouge Bayou Store', '65680 Thierer Drive', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (188, 'Raleigh Oak City Market', '008 Blaine Point', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (113, 'Albuquerque Sunset Plaza', '6 Butterfield Drive', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (140, 'Santa Barbara Riviera Retail', '74 Golf View Road', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (195, 'Minneapolis Twin Lakes Outlet', '50 Dakota Park', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (1, 'Milwaukee Lakeside Outlet', '30 Forster Center', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (174, 'Louisville Riverfront Shop', '077 Mendota Pass', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (248, 'Columbia Palmetto Store', '0 Havey Crossing', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (113, 'Scottsdale Fashion Square', '201 Banding Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (188, 'Tulsa Golden Gateway', '55472 Buell Drive', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (13, 'Helena Big Sky Shop', '7638 Northport Drive', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (304, 'Sacramento Valley View', '7473 Killdeer Parkway', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (315, 'Mobile Bay Store', '108 Troy Parkway', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (236, 'Long Beach Pacific View Store', '70 Dunning Street', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (218, 'St. Cloud River City Store', '361 Warner Plaza', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (123, 'Louisville Riverfront Shop', '8474 Gateway Junction', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (197, 'NorthPark Center', '92079 Ryan Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (259, 'Tulsa Golden Gateway', '14907 Roxbury Terrace', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (158, 'Anchorage Northern Lights Market', '3081 Lakewood Gardens Center', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (77, 'New Orleans Bourbon Street Boutique', '51 Crownhardt Pass', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (99, 'Raleigh Oak City Market', '49145 Menomonie Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (354, 'Norfolk Naval Base Boutique', '64 Sunnyside Lane', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (179, 'Santa Fe Adobe Plaza', '20996 Gerald Avenue', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (3, 'Boston Harbor Shop', '0240 Dawn Crossing', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (276, 'Washington Capitol Storefront', '4 Morningstar Parkway', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (59, 'Boulder Flatiron Boutique', '81404 Mcbride Lane', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (56, 'Charleston Southern Charm Boutique', '853 Monica Place', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (30, 'Tampa Bay Treasures', '661 Forest Dale Avenue', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (288, 'Lubbock Lonestar Plaza', '750 Trailsway Hill', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (267, 'Portland Casco Bay Store', '32940 Moose Terrace', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (25, 'Fargo Northern Lights Store', '468 Morning Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (250, 'Baton Rouge Bayou Store', '3312 Hagan Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (26, 'Long Beach Pacific View Store', '8765 Lindbergh Court', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (54, 'Newark Liberty Gateway', '6278 Hallows Circle', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (239, 'Sacramento Valley View', '4 Jenifer Drive', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (112, 'Bridgeport Coastal Junction', '0 Butterfield Center', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (26, 'Carson City Silver State Boutique', '8532 Blaine Trail', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (36, 'Atlanta Peachtree Plaza', '42 Westport Court', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (161, 'Naples Paradise Coast Store', '2 Arapahoe Crossing', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (74, 'Providence Colonial Shop', '27 Village Junction', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (274, 'Lansing Great Lakes Boutique', '5 Mandrake Place', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (213, 'Lincoln Star City Market', '79 Vahlen Way', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (293, 'Minneapolis Twin Lakes Outlet', '3 Utah Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (326, 'Charleston Harbor View Market', '18 3rd Park', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (177, 'Fashion Island', '1 Crescent Oaks Drive', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (219, 'Mobile Gulf Coast Store', '71034 Anzinger Circle', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (169, 'Fort Wayne Summit City Store', '09 Browning Drive', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (270, 'Portland Casco Bay Store', '5821 Memorial Place', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (157, 'Phoenix Desert Oasis', '196 Village Green Court', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (350, 'Salt Lake City Wasatch Store', '430 Clemons Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (207, 'Raleigh Oak City Market', '6 Sloan Park', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (259, 'Cedar City Festival Market', '4 Vermont Plaza', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (223, 'Pensacola Beachfront Boutique', '56639 Golden Leaf Terrace', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (227, 'Boise Capital Mall', '70 Heath Way', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (234, 'Burlington Lakeview Market', '54698 Delladonna Plaza', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (90, 'Fort Wayne Summit City Store', '77 Warrior Drive', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (69, 'St. Cloud River City Store', '81 Dunning Avenue', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (43, 'Erie Lakefront Mall', '5327 Sugar Hill', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (42, 'Tulsa Oil Capital Boutique', '54556 Thierer Avenue', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (73, 'Colorado Springs Peak View Market', '03 Almo Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (151, 'Louisville Riverfront Shop', '00235 Westerfield Plaza', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (289, 'Albuquerque Sunset Plaza', '69 Twin Pines Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (152, 'Newark Liberty Gateway', '90774 Maywood Center', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (90, 'Beaumont Spindletop Store', '99 Sheridan Road', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (17, 'Spokane Riverfront Mall', '837 Mcbride Park', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (263, 'Grand Rapids Furniture City Shop', '494 Golf Avenue', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (146, 'Seattle Flagship', '9647 Westerfield Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (356, 'Bloomington Mall of America', '5595 Northwestern Street', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (275, 'Sioux Falls Rushmore Mall', '02 Weeping Birch Junction', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (27, 'Spokane Riverfront Mall', '46 Susan Court', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (206, 'Pensacola Beachfront Boutique', '09347 Ludington Point', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (163, 'New Haven Elm Street Retail', '70948 Del Sol Hill', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (238, 'Bridgeport Coastal Junction', '94031 Mandrake Terrace', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (103, 'Baltimore Harbor Shop', '1483 Lien Junction', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (172, 'Lansing Great Lakes Boutique', '85694 Kennedy Circle', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (296, 'Fargo Northern Lights Store', '35061 Westport Alley', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (114, 'Lubbock Lonestar Plaza', '9 Brentwood Junction', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (312, 'St. Cloud River City Store', '746 Gina Drive', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (127, 'Tallahassee Capital Collection', '15688 Hanover Alley', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (72, 'Syracuse Salt City Shop', '74575 Lien Road', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (85, 'Green Bay Packerland Boutique', '73499 Troy Hill', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (210, 'Fargo Frontier Shop', '169 Carioca Drive', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (303, 'Lincoln Star City Market', '13236 Ridge Oak Center', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (91, 'Peoria Riverfront Plaza', '304 Springs Center', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (175, 'Wichita Windflower Boutique', '028 East Way', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (313, 'Macon Cherry Blossom Market', '4940 Shasta Plaza', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (199, 'Syracuse Salt City Shop', '8623 Scofield Way', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (284, 'Boise Gem State Store', '1 Badeau Lane', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (203, 'Durham Tobacco Road Retail', '15864 Blaine Drive', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (111, 'Long Beach Pacific View Store', '871 3rd Road', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (12, 'Lexington Bluegrass Boutique', '40879 Commercial Drive', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (100, 'Grand Rapids Furniture City Shop', '8 Rigney Parkway', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (53, 'Pensacola Beachfront Boutique', '35690 Fairfield Center', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (312, 'Baton Rouge Bayou Store', '55959 Prairieview Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (13, 'Flagstaff Ponderosa Mall', '2 Melrose Parkway', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (52, 'Richmond James River Boutique', '662 Buhler Point', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (196, 'Milwaukee Lakeside Outlet', '7395 Talmadge Parkway', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (132, 'Burlington Lakeview Market', '08407 Esker Trail', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (315, 'Salt Lake City Wasatch Store', '73 Waxwing Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (120, 'Minneapolis Twin Lakes Outlet', '03416 Spenser Circle', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (343, 'Mobile Bay Store', '1784 Portage Center', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (235, 'Tulsa Oil Capital Boutique', '2025 Prairieview Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (31, 'Manchester Granite Shop', '39066 Summerview Way', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (325, 'Grand Rapids Furniture City Shop', '06 Johnson Way', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (42, 'Richmond James River Boutique', '0729 Welch Trail', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (161, 'Wichita Windflower Boutique', '087 Basil Way', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (270, 'Seattle Flagship', '289 Prairieview Center', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (249, 'Waco Brazos Mall', '72042 Vera Hill', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (127, 'Lincoln Star City Market', '2 Southridge Road', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (302, 'Dallas Lone Star Center', '720 Mallard Way', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (92, 'Salt Lake City Peaks Boutique', '6367 Rieder Road', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (157, 'Pensacola Beachfront Boutique', '35 Clemons Street', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (201, 'Baton Rouge Bayou Store', '6 Dayton Drive', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (38, 'Birmingham Iron City Mall', '814 Hansons Hill', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (338, 'Pueblo Iron Horse Store', '2 Del Mar Trail', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (182, 'Tampa Bay Treasures', '4 Duke Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (184, 'Chicago Riverwalk Outlet', '083 Haas Park', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (352, 'Asheville Blue Ridge Boutique', '724 Spaight Junction', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (343, 'Seattle Flagship', '9214 Lotheville Way', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (86, 'Waco Brazos Mall', '68327 Artisan Way', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (272, 'Yonkers Hudson Line Store', '690 Artisan Drive', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (334, 'Seattle Flagship', '7 Delaware Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (280, 'Albuquerque Sunset Plaza', '70 Caliangt Place', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (6, 'Fashion Island', '85273 Stephen Hill', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (275, 'Stockton Golden Poppy Shop', '55 Gerald Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (257, 'Long Beach Pacific View Store', '921 Ronald Regan Crossing', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (238, 'Sioux Falls Rushmore Mall', '45 Hollow Ridge Circle', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (224, 'Honolulu Beachwalk', '92 Thackeray Road', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (50, 'Atlanta Peachtree Plaza', '5 Park Meadow Avenue', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (217, 'Boise Riverwalk Market', '25211 Darwin Court', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (204, 'Wichita Windflower Boutique', '1049 Mcbride Road', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (317, 'Grand Rapids Furniture City Shop', '930 Eggendart Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (222, 'Bangor Pine Tree Shop', '23 Blaine Center', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (299, 'Syracuse Salt City Shop', '393 Fuller Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (219, 'Baton Rouge Bayou Store', '3 Fairview Hill', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (22, 'Washington Capitol Storefront', '46 Menomonie Trail', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (204, 'Trenton Liberty Hall', '16 Hanson Hill', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (29, 'Austin Live Music Store', '5 Erie Pass', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (28, 'Pensacola Beachfront Boutique', '5407 Linden Avenue', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (354, 'Augusta Pine Tree Boutique', '72 Saint Paul Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (31, 'Chicago Riverwalk Outlet', '077 Tennessee Parkway', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (265, 'Myrtle Beach Palmetto Place', '29 Lillian Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (135, 'Atlanta Peachtree Plaza', '5 Florence Avenue', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (334, 'Louisville Riverfront Shop', '69 4th Center', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (134, 'Baton Rouge Bayou Store', '65 Bultman Center', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (185, 'Austin Live Music Store', '54 Northridge Court', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (86, 'Providence Colonial Shop', '69 Melby Junction', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (250, 'Louisville Riverfront Shop', '19657 Dakota Alley', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (282, 'Beaumont Spindletop Store', '46 Hagan Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (333, 'Virginia Beach Surfside Store', '36 Basil Way', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (287, 'Anchorage Northern Star Boutique', '925 Summer Ridge Circle', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (220, 'Durham Tobacco Road Retail', '98933 Holmberg Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (46, 'New Haven Elm Street Retail', '59 Laurel Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (140, 'El Paso Border Town Market', '50794 Mosinee Plaza', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (314, 'Tulsa Golden Gateway', '23 Mayer Way', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (263, 'Reno Biggest Little City Store', '1 Pleasure Court', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (347, 'Manhattan Midtown Mart', '23 Pepper Wood Point', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (174, 'St. Cloud River City Store', '37303 Toban Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (249, 'Orlando Magic Mart', '60 Everett Trail', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (231, 'Baton Rouge Bayou Store', '69 Esch Trail', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (95, 'Louisville Riverfront Shop', '7 Northfield Trail', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (11, 'Fort Wayne Summit City Store', '3219 Brickson Park Hill', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (321, 'Fashion Island', '73446 Eggendart Alley', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (293, 'Charleston Harbor View Market', '1235 Farmco Place', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (339, 'Baltimore Harbor Shop', '74621 Cambridge Avenue', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (138, 'Richmond James River Boutique', '34 Fair Oaks Hill', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (18, 'Columbia Palmetto Store', '56 Hazelcrest Drive', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (90, 'Scottsdale Fashion Square', '32069 Prentice Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (280, 'Akron Rubber City Shop', '4262 Cambridge Street', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (130, 'Indianapolis Crossroads Store', '0 Beilfuss Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (170, 'Lincoln Star City Market', '81413 Butternut Center', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (218, 'Lincoln Capitol View Market', '5 Oneill Road', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (134, 'Modesto Central Valley Plaza', '433 Melrose Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (254, 'Milwaukee Lakeside Outlet', '90 Oneill Junction', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (10, 'Nashville Music Row Mart', '4812 Monterey Street', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (220, 'Denver Mountain Mall', '96596 Lillian Lane', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (2, 'Sioux Falls Rushmore Mall', '45783 Petterle Terrace', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (226, 'Lubbock Lonestar Plaza', '00452 4th Place', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (58, 'Waco Brazos Mall', '8 Macpherson Place', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (114, 'Corpus Christi Bayfront Shop', '92 Northridge Terrace', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (288, 'Grand Rapids Furniture City Shop', '33 Sunbrook Point', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (108, 'Baltimore Harbor Shop', '74473 Browning Alley', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (49, 'Boston Harbor Shop', '9416 Graceland Pass', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (179, 'Lubbock Hub City Store', '51 Elgar Trail', 'Southwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (65, 'Bloomington Mall of America', '23702 Fairfield Junction', 'South');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (105, 'New Haven Elm Street Retail', '58599 Oxford Point', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (39, 'Indianapolis Crossroads Store', '73638 Laurel Terrace', 'Northwest');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (283, 'Greensboro Gate City Boutique', '9954 Westerfield Pass', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (54, 'Cheyenne Frontier Store', '74329 Waubesa Terrace', 'East Coast');
insert into tblStore (StoreNumber, StoreName, StoreAddress, StoreDivision) values (273, 'Tulsa Golden Gateway', '6 Longview Terrace', 'East Coast');



-- DELETE FROM tblStore;

SELECT * FROM tblStore